[program:flask_app]
command=python3 -u /home/mesbot/server.py
directory=/home/mesbot/
user=mesbot
autostart=true
autorestart=true
stderr_logfile=/var/log/flask_app.log
stdout_logfile=/var/log/flask_app.log
redirect_stderr=true
