[program:discord_app]
command=python3 -u /home/mesbot/main.py
directory=/home/mesbot/
user=mesbot
autostart=true
autorestart=true
stderr_logfile=/var/log/discord_app.log
stdout_logfile=/var/log/discord_app.log
redirect_stderr=true
